export const PERMISSIONS = {
  ADMIN_USERS_VIEW: 'ADMIN_USERS_VIEW',
  ADMIN_DOCS_VIEW: 'ADMIN_DOCS_VIEW',
  ADMIN_DATA_VIEW: 'ADMIN_DATA_VIEW',
  ADMIN_MATCH_VIEW: 'ADMIN_MATCH_VIEW',
  ADMIN_MONITOR_VIEW: 'ADMIN_MONITOR_VIEW',
  ADMIN_AUDIT_VIEW: 'ADMIN_AUDIT_VIEW',
} as const

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

